-- MySQL Script generated by MySQL Workbench
-- mié 21 dic 2016 13:06:21 CST
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema melisa
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema melisa
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `melisa` DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ;
USE `melisa` ;

-- -----------------------------------------------------
-- Table `melisa`.`users`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `melisa`.`users` (
  `id` VARCHAR(36) NOT NULL,
  `name` VARCHAR(30) NOT NULL,
  `password` VARCHAR(60) NOT NULL,
  `email` VARCHAR(90) NOT NULL,
  `createdAt` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `active` TINYINT NOT NULL DEFAULT 1,
  `isSystem` TINYINT NOT NULL DEFAULT 0,
  `firstLogin` TINYINT NOT NULL DEFAULT 0,
  `changePassword` TINYINT NOT NULL DEFAULT 0,
  `isGod` TINYINT NOT NULL DEFAULT 0,
  `updatedAt` DATETIME NULL,
  `rememberToken` VARCHAR(100) NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `name_UNIQUE` (`name` ASC),
  INDEX `name_INDEX` (`name` ASC),
  UNIQUE INDEX `email_UNIQUE` (`email` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `melisa`.`profiles`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `melisa`.`profiles` (
  `id` SMALLINT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(75) NOT NULL,
  `key` VARCHAR(20) NOT NULL,
  `isSystem` TINYINT NOT NULL DEFAULT 0,
  `active` TINYINT NOT NULL DEFAULT 1,
  `createdAt` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updatedAt` DATETIME NULL,
  `icon` VARCHAR(45) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `melisa`.`identities`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `melisa`.`identities` (
  `id` VARCHAR(36) NOT NULL,
  `idProfile` SMALLINT NOT NULL,
  `display` VARCHAR(75) NOT NULL,
  `displayEspecific` VARCHAR(75) NOT NULL,
  `active` TINYINT NOT NULL DEFAULT 1,
  `isSystem` TINYINT NOT NULL DEFAULT 0,
  `isDefault` TINYINT NOT NULL DEFAULT 0,
  `createdAt` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updatedAt` DATETIME NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_identities_profiles_idx` (`idProfile` ASC),
  UNIQUE INDEX `displayEspecific_UNIQUE` (`displayEspecific` ASC),
  CONSTRAINT `fk_identities_profiles`
    FOREIGN KEY (`idProfile`)
    REFERENCES `melisa`.`profiles` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `melisa`.`usersIdentities`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `melisa`.`usersIdentities` (
  `id` VARCHAR(36) NOT NULL,
  `idUser` VARCHAR(36) NOT NULL,
  `idIdentity` VARCHAR(36) NOT NULL,
  `createdAt` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  INDEX `fk_usersIdentities_users1_idx` (`idUser` ASC),
  INDEX `fk_usersIdentities_identities1_idx` (`idIdentity` ASC),
  UNIQUE INDEX `idIdentity_UNIQUE` (`idIdentity` ASC),
  CONSTRAINT `fk_usersIdentities_users1`
    FOREIGN KEY (`idUser`)
    REFERENCES `melisa`.`users` (`id`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_usersIdentities_identities1`
    FOREIGN KEY (`idIdentity`)
    REFERENCES `melisa`.`identities` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `melisa`.`robots`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `melisa`.`robots` (
  `id` VARCHAR(36) NOT NULL,
  `name` VARCHAR(65) NOT NULL,
  `key` VARCHAR(65) NOT NULL,
  `description` VARCHAR(200) NOT NULL,
  `active` TINYINT NOT NULL,
  `createdAt` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updatedAt` DATETIME NULL,
  PRIMARY KEY (`id`),
  CONSTRAINT `fk_robots_identities1`
    FOREIGN KEY (`id`)
    REFERENCES `melisa`.`identities` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `melisa`.`applications`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `melisa`.`applications` (
  `id` VARCHAR(36) NOT NULL,
  `name` VARCHAR(45) NOT NULL,
  `description` VARCHAR(100) NOT NULL,
  `key` VARCHAR(65) NOT NULL,
  `active` TINYINT NOT NULL DEFAULT 1,
  `iconClassSmall` VARCHAR(45) NOT NULL DEFAULT 'fa fa-cube fa-lg',
  `iconClassMedium` VARCHAR(75) NOT NULL DEFAULT 'fa fa-cube fa-3x',
  `iconClassLarge` VARCHAR(75) NOT NULL DEFAULT 'fa fa-cube fa-5x',
  `nameSpace` VARCHAR(75) NOT NULL,
  `typeSecurity` VARCHAR(10) NOT NULL DEFAULT 'art',
  `isSystem` TINYINT NOT NULL DEFAULT 0,
  `createdAt` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `version` VARCHAR(8) NOT NULL DEFAULT '1.0.0',
  `updatedAt` DATETIME NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `key_UNIQUE` (`key` ASC),
  UNIQUE INDEX `name_UNIQUE` (`name` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `melisa`.`applicationsRoles`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `melisa`.`applicationsRoles` (
  `id` VARCHAR(36) NOT NULL,
  `idApplication` VARCHAR(36) NOT NULL,
  `idIdentityCreated` VARCHAR(36) NOT NULL,
  `rol` VARCHAR(75) NOT NULL,
  `active` TINYINT NOT NULL DEFAULT 1,
  `createdAt` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `description` VARCHAR(100) NOT NULL,
  `isSystem` TINYINT NOT NULL DEFAULT 0,
  `updatedAt` DATETIME NULL,
  `idIdentityUpdated` VARCHAR(36) NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_applicationsRoles_applications1_idx` (`idApplication` ASC),
  INDEX `fk_applicationsRoles_identities1_idx` (`idIdentityCreated` ASC),
  UNIQUE INDEX `idApplication_rol_UNIQUE` (`idApplication` ASC, `rol` ASC),
  CONSTRAINT `fk_applicationsRoles_applications1`
    FOREIGN KEY (`idApplication`)
    REFERENCES `melisa`.`applications` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_applicationsRoles_identities1`
    FOREIGN KEY (`idIdentityCreated`)
    REFERENCES `melisa`.`identities` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `melisa`.`tasks`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `melisa`.`tasks` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `key` VARCHAR(255) NOT NULL,
  `name` VARCHAR(255) NOT NULL,
  `active` TINYINT NOT NULL DEFAULT 1,
  `isSystem` TINYINT NOT NULL DEFAULT 0,
  `description` VARCHAR(250) NOT NULL,
  `pattern` SMALLINT NOT NULL DEFAULT 8 COMMENT 'ENUM(\'all\',\'all.crud\',\'all.create\',\'all.read\',\'all.update\',\'all.delete\',\'all.access\',\'access\',\'create\',\'read\',\'update\',\'delete\',\'select\',\'service\',\'library\')',
  PRIMARY KEY (`id`),
  UNIQUE INDEX `key_UNIQUE` (`key` ASC),
  INDEX `key_INDEX` (`key` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `melisa`.`applicationsRT`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `melisa`.`applicationsRT` (
  `id` VARCHAR(36) NOT NULL,
  `idApplicationRol` VARCHAR(36) NOT NULL,
  `idTask` INT NOT NULL,
  `idIdentityCreated` VARCHAR(36) NOT NULL,
  `active` TINYINT NOT NULL,
  `createdAt` DATETIME NOT NULL,
  `isSystem` TINYINT NOT NULL,
  `updatedAt` DATETIME NULL,
  `idIdentityUpdated` VARCHAR(36) NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_applicationsRT_applicationsRoles1_idx` (`idApplicationRol` ASC),
  INDEX `fk_applicationsRT_tasks1_idx` (`idTask` ASC),
  INDEX `fk_applicationsRT_identities1_idx` (`idIdentityCreated` ASC),
  UNIQUE INDEX `idApplicationRol_idTask_UNIQUE` (`idApplicationRol` ASC, `idTask` ASC),
  INDEX `idApplicationRol_INDEX` (`idApplicationRol` ASC),
  CONSTRAINT `fk_applicationsRT_applicationsRoles1`
    FOREIGN KEY (`idApplicationRol`)
    REFERENCES `melisa`.`applicationsRoles` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_applicationsRT_tasks1`
    FOREIGN KEY (`idTask`)
    REFERENCES `melisa`.`tasks` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_applicationsRT_identities1`
    FOREIGN KEY (`idIdentityCreated`)
    REFERENCES `melisa`.`identities` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `melisa`.`scopes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `melisa`.`scopes` (
  `id` SMALLINT NOT NULL,
  `name` VARCHAR(75) NOT NULL,
  `active` TINYINT NOT NULL DEFAULT 1,
  `createdAt` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updatedAt` DATETIME NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `melisa`.`applicationsRS`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `melisa`.`applicationsRS` (
  `id` VARCHAR(36) NOT NULL,
  `idApplicationRol` VARCHAR(36) NOT NULL,
  `idScope` SMALLINT NOT NULL,
  `idIdentityCreated` VARCHAR(36) NOT NULL,
  `isDefault` TINYINT NOT NULL DEFAULT 0,
  `active` TINYINT NOT NULL DEFAULT 1,
  `createdAt` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updatedAt` DATETIME NULL,
  `idIdentityUpdate` VARCHAR(36) NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_applicationsRS_applicationsRoles1_idx` (`idApplicationRol` ASC),
  INDEX `fk_applicationsRS_scopes1_idx` (`idScope` ASC),
  INDEX `fk_applicationsRS_identities1_idx` (`idIdentityCreated` ASC),
  UNIQUE INDEX `idApplicationRol_idScope_UNIQUE` (`idApplicationRol` ASC, `idScope` ASC),
  INDEX `idApplicationRol_INDEX` (`idApplicationRol` ASC),
  CONSTRAINT `fk_applicationsRS_applicationsRoles1`
    FOREIGN KEY (`idApplicationRol`)
    REFERENCES `melisa`.`applicationsRoles` (`id`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_applicationsRS_scopes1`
    FOREIGN KEY (`idScope`)
    REFERENCES `melisa`.`scopes` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_applicationsRS_identities1`
    FOREIGN KEY (`idIdentityCreated`)
    REFERENCES `melisa`.`identities` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `melisa`.`menus`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `melisa`.`menus` (
  `id` SMALLINT NOT NULL AUTO_INCREMENT,
  `key` VARCHAR(65) NOT NULL,
  `name` VARCHAR(200) NOT NULL,
  `createdAt` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `key_UNIQUE` (`key` ASC),
  INDEX `key_INDEX` (`key` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `melisa`.`options`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `melisa`.`options` (
  `id` SMALLINT NOT NULL AUTO_INCREMENT,
  `key` VARCHAR(65) NOT NULL,
  `name` VARCHAR(255) NOT NULL,
  `isSubMenu` TINYINT NOT NULL DEFAULT 0,
  `iconClassSmall` VARCHAR(75) NULL DEFAULT 'fa fa-cog fa-lg',
  `iconClassMedium` VARCHAR(75) NULL DEFAULT 'fa fa-cog fa-3x',
  `iconClassLarge` VARCHAR(75) NULL DEFAULT 'fa fa-cog fa-5x',
  `text` VARCHAR(75) NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `key_UNIQUE` (`key` ASC),
  INDEX `key_INDEX` (`key` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `melisa`.`menusOptions`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `melisa`.`menusOptions` (
  `id` SMALLINT NOT NULL AUTO_INCREMENT,
  `idMenu` SMALLINT NOT NULL,
  `idOption` SMALLINT NOT NULL,
  `order` SMALLINT NOT NULL DEFAULT 0,
  `idOptionParent` SMALLINT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_menusOptions_menus1_idx` (`idMenu` ASC),
  INDEX `fk_menusOptions_options1_idx` (`idOption` ASC),
  UNIQUE INDEX `idMenu_idOption_UNIQUE` (`idMenu` ASC, `idOption` ASC),
  CONSTRAINT `fk_menusOptions_menus1`
    FOREIGN KEY (`idMenu`)
    REFERENCES `melisa`.`menus` (`id`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_menusOptions_options1`
    FOREIGN KEY (`idOption`)
    REFERENCES `melisa`.`options` (`id`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `melisa`.`optionsTasks`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `melisa`.`optionsTasks` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `idOption` SMALLINT NOT NULL,
  `idTask` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_optionsTasks_options1_idx` (`idOption` ASC),
  INDEX `fk_optionsTasks_tasks1_idx` (`idTask` ASC),
  CONSTRAINT `fk_optionsTasks_options1`
    FOREIGN KEY (`idOption`)
    REFERENCES `melisa`.`options` (`id`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_optionsTasks_tasks1`
    FOREIGN KEY (`idTask`)
    REFERENCES `melisa`.`tasks` (`id`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `melisa`.`applicationsRST`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `melisa`.`applicationsRST` (
  `id` VARCHAR(36) NOT NULL,
  `idApplicationRS` VARCHAR(36) NOT NULL,
  `idTask` INT NOT NULL,
  `idIdentityCreated` VARCHAR(36) NOT NULL,
  `active` TINYINT NOT NULL DEFAULT 1,
  `createdAt` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `idIdentityUpdated` VARCHAR(36) NULL,
  `updatedAt` DATETIME NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_applicationsRST_applicationsRS1_idx` (`idApplicationRS` ASC),
  INDEX `fk_applicationsRST_tasks1_idx` (`idTask` ASC),
  INDEX `fk_applicationsRST_identities1_idx` (`idIdentityCreated` ASC),
  UNIQUE INDEX `idApplicationRS_idTask_UNIQUE` (`idApplicationRS` ASC, `idTask` ASC),
  INDEX `idApplicationRS_INDEX` (`idApplicationRS` ASC),
  CONSTRAINT `fk_applicationsRST_applicationsRS1`
    FOREIGN KEY (`idApplicationRS`)
    REFERENCES `melisa`.`applicationsRS` (`id`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_applicationsRST_tasks1`
    FOREIGN KEY (`idTask`)
    REFERENCES `melisa`.`tasks` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_applicationsRST_identities1`
    FOREIGN KEY (`idIdentityCreated`)
    REFERENCES `melisa`.`identities` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `melisa`.`modules`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `melisa`.`modules` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(255) NOT NULL,
  `url` VARCHAR(150) NOT NULL,
  `active` TINYINT NOT NULL DEFAULT 1,
  `version` VARCHAR(8) NOT NULL,
  `description` VARCHAR(200) NOT NULL,
  `iconClassSmall` VARCHAR(75) NOT NULL DEFAULT 'fa fa-window-maximize fa-lg',
  `iconClassMedium` VARCHAR(75) NOT NULL DEFAULT 'fa fa-window-maximize fa-3x',
  `iconClassLarge` VARCHAR(75) NOT NULL DEFAULT 'fa fa-window-maximize fa-5x',
  `nameSpace` VARCHAR(255) NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `name_url_UNIQUE` (`name` ASC, `url` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `melisa`.`modulesTasks`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `melisa`.`modulesTasks` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `idModule` INT NOT NULL,
  `idTask` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_modulesTasks_modules1_idx` (`idModule` ASC),
  INDEX `fk_modulesTasks_tasks1_idx` (`idTask` ASC),
  UNIQUE INDEX `idModule_idTask_UNIQUE` (`idModule` ASC, `idTask` ASC),
  CONSTRAINT `fk_modulesTasks_modules1`
    FOREIGN KEY (`idModule`)
    REFERENCES `melisa`.`modules` (`id`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_modulesTasks_tasks1`
    FOREIGN KEY (`idTask`)
    REFERENCES `melisa`.`tasks` (`id`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `melisa`.`events`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `melisa`.`events` (
  `id` VARCHAR(36) NOT NULL,
  `key` VARCHAR(150) NOT NULL,
  `description` VARCHAR(100) NOT NULL,
  `isSystem` TINYINT NOT NULL DEFAULT 0,
  `createdAt` DATETIME NOT NULL,
  `updatedAt` DATETIME NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `key_UNIQUE` (`key` ASC),
  INDEX `key_INDEX` (`key` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `melisa`.`binnacleStatus`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `melisa`.`binnacleStatus` (
  `id` SMALLINT NOT NULL,
  `name` VARCHAR(75) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `name_UNIQUE` (`name` ASC),
  INDEX `name_INDEX` (`name` ASC))
ENGINE = InnoDB
COMMENT = '1 nuevo, 2 procesando, 3 procesado, 4 cancelado, 5 procesado con errores';


-- -----------------------------------------------------
-- Table `melisa`.`binnacle`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `melisa`.`binnacle` (
  `id` VARCHAR(36) NOT NULL,
  `idBinnacleStatus` SMALLINT NOT NULL DEFAULT 1,
  `idEvent` VARCHAR(36) NOT NULL,
  `idIdentityCreated` VARCHAR(36) NOT NULL,
  `createdAt` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `isProcessed` TINYINT NOT NULL,
  `idIdentityUpdated` VARCHAR(36) NULL,
  `data` TEXT NULL,
  `processedAt` DATETIME NULL,
  `updatedAt` DATETIME NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_binnacle_binnacleStatus1_idx` (`idBinnacleStatus` ASC),
  INDEX `fk_binnacle_events1_idx` (`idEvent` ASC),
  INDEX `fk_binnacle_identities1_idx` (`idIdentityCreated` ASC),
  CONSTRAINT `fk_binnacle_binnacleStatus1`
    FOREIGN KEY (`idBinnacleStatus`)
    REFERENCES `melisa`.`binnacleStatus` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_binnacle_events1`
    FOREIGN KEY (`idEvent`)
    REFERENCES `melisa`.`events` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_binnacle_identities1`
    FOREIGN KEY (`idIdentityCreated`)
    REFERENCES `melisa`.`identities` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `melisa`.`binnacleListenersStatus`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `melisa`.`binnacleListenersStatus` (
  `id` SMALLINT NOT NULL,
  `name` VARCHAR(75) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `name_UNIQUE` (`name` ASC),
  INDEX `name_INDEX` (`name` ASC))
ENGINE = InnoDB
COMMENT = '1 nuevo, 2 procesando, 3 procesado, 4 cancelado, 5 procesado con errores';


-- -----------------------------------------------------
-- Table `melisa`.`listeners`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `melisa`.`listeners` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `idEvent` VARCHAR(36) NOT NULL,
  `idModule` INT NOT NULL,
  `active` TINYINT NOT NULL,
  `createdAt` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updatedAt` DATETIME NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_listeners_events1_idx` (`idEvent` ASC),
  INDEX `fk_listeners_modules1_idx` (`idModule` ASC),
  UNIQUE INDEX `idEvent_idModule_UNIQUE` (`idEvent` ASC, `idModule` ASC),
  CONSTRAINT `fk_listeners_events1`
    FOREIGN KEY (`idEvent`)
    REFERENCES `melisa`.`events` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_listeners_modules1`
    FOREIGN KEY (`idModule`)
    REFERENCES `melisa`.`modules` (`id`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `melisa`.`binnacleListeners`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `melisa`.`binnacleListeners` (
  `id` VARCHAR(36) NOT NULL,
  `idBinnacleListenerStatus` SMALLINT NOT NULL DEFAULT 1,
  `idBinnacle` VARCHAR(36) NOT NULL,
  `idListener` INT NOT NULL,
  `idIdentityCreated` VARCHAR(36) NOT NULL,
  `createdAt` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `idIdentityUpdated` VARCHAR(36) NULL,
  `updatedAt` DATETIME NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_binnacleListeners_binnacleListenersStatus1_idx` (`idBinnacleListenerStatus` ASC),
  INDEX `fk_binnacleListeners_binnacle1_idx` (`idBinnacle` ASC),
  INDEX `fk_binnacleListeners_listeners1_idx` (`idListener` ASC),
  INDEX `idBinnacle_INDEX` (`idBinnacle` ASC),
  INDEX `fk_binnacleListeners_identities1_idx` (`idIdentityCreated` ASC),
  CONSTRAINT `fk_binnacleListeners_binnacleListenersStatus1`
    FOREIGN KEY (`idBinnacleListenerStatus`)
    REFERENCES `melisa`.`binnacleListenersStatus` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_binnacleListeners_binnacle1`
    FOREIGN KEY (`idBinnacle`)
    REFERENCES `melisa`.`binnacle` (`id`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_binnacleListeners_listeners1`
    FOREIGN KEY (`idListener`)
    REFERENCES `melisa`.`listeners` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_binnacleListeners_identities1`
    FOREIGN KEY (`idIdentityCreated`)
    REFERENCES `melisa`.`identities` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `melisa`.`binnacleListenersErrors`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `melisa`.`binnacleListenersErrors` (
  `id` VARCHAR(36) NOT NULL,
  `idBinnacleListener` VARCHAR(36) NOT NULL,
  `error` TEXT NOT NULL,
  `createdAt` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  INDEX `fk_binnacleListenersErrors_binnacleListeners1_idx` (`idBinnacleListener` ASC),
  CONSTRAINT `fk_binnacleListenersErrors_binnacleListeners1`
    FOREIGN KEY (`idBinnacleListener`)
    REFERENCES `melisa`.`binnacleListeners` (`id`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `melisa`.`authentications`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `melisa`.`authentications` (
  `id` SMALLINT NOT NULL,
  `idAuthenticationProvider` SMALLINT NOT NULL,
  `active` TINYINT NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `melisa`.`passwordResets`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `melisa`.`passwordResets` (
  `email` VARCHAR(90) NOT NULL,
  `token` VARCHAR(90) NOT NULL,
  `createdAt` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`email`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `melisa`.`people`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `melisa`.`people` (
  `id` VARCHAR(36) NOT NULL,
  `name` VARCHAR(45) NOT NULL,
  `firstName` VARCHAR(45) NOT NULL,
  `lastName` VARCHAR(45) NOT NULL,
  `nickname` VARCHAR(45) NOT NULL,
  `gender` TINYINT NOT NULL DEFAULT 1,
  `createdAt` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `birthday` DATE NULL,
  `updatedAt` DATETIME NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `name_firstName_lastName_UNIQUE` (`name` ASC, `firstName` ASC, `lastName` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `melisa`.`redirects`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `melisa`.`redirects` (
  `id` VARCHAR(36) NOT NULL,
  `idApplication` VARCHAR(36) NOT NULL,
  `idIdentityCreated` VARCHAR(36) NOT NULL,
  `name` VARCHAR(75) NOT NULL,
  `active` TINYINT NOT NULL DEFAULT 1,
  `createdAt` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `idIdentityUpdated` VARCHAR(36) NULL,
  `description` VARCHAR(200) NULL,
  `path` VARCHAR(45) NULL,
  `updatedAt` DATETIME NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_redirects_applications1_idx` (`idApplication` ASC),
  INDEX `fk_redirects_identities1_idx` (`idIdentityCreated` ASC),
  UNIQUE INDEX `name_UNIQUE` (`name` ASC),
  CONSTRAINT `fk_redirects_applications1`
    FOREIGN KEY (`idApplication`)
    REFERENCES `melisa`.`applications` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_redirects_identities1`
    FOREIGN KEY (`idIdentityCreated`)
    REFERENCES `melisa`.`identities` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `melisa`.`redirectsIdentities`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `melisa`.`redirectsIdentities` (
  `id` VARCHAR(36) NOT NULL,
  `idRedirect` VARCHAR(36) NOT NULL,
  `idIdentityCreated` VARCHAR(36) NOT NULL,
  `idIdentityRedirect` VARCHAR(36) NOT NULL,
  `active` TINYINT NOT NULL DEFAULT 1,
  `createdAt` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `idIdentityUpdated` VARCHAR(36) NULL,
  `updatedAt` DATETIME NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_redirectsIdentities_redirects1_idx` (`idRedirect` ASC),
  INDEX `fk_redirectsIdentities_identities1_idx` (`idIdentityCreated` ASC),
  INDEX `fk_redirectsIdentities_identities2_idx` (`idIdentityRedirect` ASC),
  UNIQUE INDEX `idRedirect_idIdentityRedirect_UNIQUE` (`idRedirect` ASC, `idIdentityRedirect` ASC),
  INDEX `idRedirect_INDEX` (`idRedirect` ASC),
  CONSTRAINT `fk_redirectsIdentities_redirects1`
    FOREIGN KEY (`idRedirect`)
    REFERENCES `melisa`.`redirects` (`id`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_redirectsIdentities_identities1`
    FOREIGN KEY (`idIdentityCreated`)
    REFERENCES `melisa`.`identities` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_redirectsIdentities_identities2`
    FOREIGN KEY (`idIdentityRedirect`)
    REFERENCES `melisa`.`identities` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `melisa`.`groups`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `melisa`.`groups` (
  `id` VARCHAR(36) NOT NULL,
  `name` VARCHAR(75) NOT NULL,
  `description` VARCHAR(100) NOT NULL,
  `createdAt` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updatedAt` DATETIME NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `name_UNIQUE` (`name` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `melisa`.`redirectsGroups`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `melisa`.`redirectsGroups` (
  `id` VARCHAR(36) NOT NULL,
  `idRedirect` VARCHAR(36) NOT NULL,
  `idIdentityCreated` VARCHAR(36) NOT NULL,
  `idGroup` VARCHAR(36) NOT NULL,
  `active` TINYINT NOT NULL DEFAULT 1,
  `createdAt` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `idIdentityUpdated` VARCHAR(36) NULL,
  `updatedAt` DATETIME NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_redirectsGroups_redirects1_idx` (`idRedirect` ASC),
  INDEX `fk_redirectsGroups_identities1_idx` (`idIdentityCreated` ASC),
  INDEX `fk_redirectsGroups_groups1_idx` (`idGroup` ASC),
  UNIQUE INDEX `idRedirect_idGroup_UNIQUE` (`idRedirect` ASC, `idGroup` ASC),
  INDEX `idRedirect_INDEX` (`idRedirect` ASC),
  CONSTRAINT `fk_redirectsGroups_redirects1`
    FOREIGN KEY (`idRedirect`)
    REFERENCES `melisa`.`redirects` (`id`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_redirectsGroups_identities1`
    FOREIGN KEY (`idIdentityCreated`)
    REFERENCES `melisa`.`identities` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_redirectsGroups_groups1`
    FOREIGN KEY (`idGroup`)
    REFERENCES `melisa`.`groups` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `melisa`.`redirectsProfiles`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `melisa`.`redirectsProfiles` (
  `id` VARCHAR(36) NOT NULL,
  `idRedirect` VARCHAR(36) NOT NULL,
  `idIdentityCreated` VARCHAR(36) NOT NULL,
  `idProfile` SMALLINT NOT NULL,
  `active` TINYINT NOT NULL DEFAULT 1,
  `createdAt` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `idIdentityUpdated` VARCHAR(36) NULL,
  `updatedAt` DATETIME NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_redirectsProfiles_redirects1_idx` (`idRedirect` ASC),
  INDEX `fk_redirectsProfiles_identities1_idx` (`idIdentityCreated` ASC),
  INDEX `fk_redirectsProfiles_profiles1_idx` (`idProfile` ASC),
  UNIQUE INDEX `idRedirect_idProfile_UNIQUE` (`idRedirect` ASC, `idProfile` ASC),
  INDEX `idRedirect_INDEX` (`idRedirect` ASC),
  CONSTRAINT `fk_redirectsProfiles_redirects1`
    FOREIGN KEY (`idRedirect`)
    REFERENCES `melisa`.`redirects` (`id`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_redirectsProfiles_identities1`
    FOREIGN KEY (`idIdentityCreated`)
    REFERENCES `melisa`.`identities` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_redirectsProfiles_profiles1`
    FOREIGN KEY (`idProfile`)
    REFERENCES `melisa`.`profiles` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `melisa`.`assetsTypes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `melisa`.`assetsTypes` (
  `id` SMALLINT NOT NULL,
  `name` VARCHAR(75) NOT NULL,
  `key` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `name_UNIQUE` (`name` ASC),
  UNIQUE INDEX `key_UNIQUE` (`key` ASC))
ENGINE = InnoDB
COMMENT = '1 js, 2 css, 3 jpg, 4 png';


-- -----------------------------------------------------
-- Table `melisa`.`assets`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `melisa`.`assets` (
  `id` VARCHAR(150) NOT NULL,
  `idAssetType` SMALLINT NOT NULL,
  `name` VARCHAR(75) NOT NULL,
  `version` VARCHAR(8) NOT NULL DEFAULT '1.0',
  `path` VARCHAR(150) NOT NULL,
  `createdAt` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updatedAt` DATETIME NULL,
  `cdn` VARCHAR(150) NULL,
  `extraParams` VARCHAR(100) NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_assets_assetsType1_idx` (`idAssetType` ASC),
  UNIQUE INDEX `name_UNIQUE` (`name` ASC),
  INDEX `key_INDEX` (`name` ASC),
  CONSTRAINT `fk_assets_assetsType1`
    FOREIGN KEY (`idAssetType`)
    REFERENCES `melisa`.`assetsTypes` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `melisa`.`packageAssets`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `melisa`.`packageAssets` (
  `id` VARCHAR(150) NOT NULL,
  `name` VARCHAR(75) NOT NULL,
  `version` VARCHAR(8) NOT NULL DEFAULT '1.0',
  `createdAt` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updatedAt` VARCHAR(45) NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `name_UNIQUE` (`name` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `melisa`.`packageAssetsItems`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `melisa`.`packageAssetsItems` (
  `id` SMALLINT NOT NULL AUTO_INCREMENT,
  `idPackageAsset` VARCHAR(150) NOT NULL,
  `idAsset` VARCHAR(150) NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_packageAssetsItems_packageAssets1_idx` (`idPackageAsset` ASC),
  INDEX `fk_packageAssetsItems_assets1_idx` (`idAsset` ASC),
  CONSTRAINT `fk_packageAssetsItems_packageAssets1`
    FOREIGN KEY (`idPackageAsset`)
    REFERENCES `melisa`.`packageAssets` (`id`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_packageAssetsItems_assets1`
    FOREIGN KEY (`idAsset`)
    REFERENCES `melisa`.`assets` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `melisa`.`translationsLanguages`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `melisa`.`translationsLanguages` (
  `id` CHAR(2) NOT NULL,
  `name` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `melisa`.`translations`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `melisa`.`translations` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `idTranslationLanguage` CHAR(2) NOT NULL,
  `key` VARCHAR(150) NOT NULL,
  `text` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_translations_translationsLanguages1_idx` (`idTranslationLanguage` ASC),
  UNIQUE INDEX `idTranslationLanguage_key_UNIQUE` (`idTranslationLanguage` ASC, `key` ASC),
  CONSTRAINT `fk_translations_translationsLanguages1`
    FOREIGN KEY (`idTranslationLanguage`)
    REFERENCES `melisa`.`translationsLanguages` (`id`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `melisa`.`passwordless`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `melisa`.`passwordless` (
  `id` VARCHAR(36) NOT NULL,
  `idUser` VARCHAR(36) NOT NULL,
  `idIdentityCreated` VARCHAR(36) NOT NULL,
  `name` VARCHAR(65) NOT NULL,
  `active` TINYINT NOT NULL,
  `createdAt` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `idIdentityUpdated` VARCHAR(36) NULL,
  `updatedAt` DATETIME NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `name_UNIQUE` (`name` ASC),
  INDEX `fk_passwordless_users1_idx` (`idUser` ASC),
  INDEX `fk_passwordless_identities1_idx` (`idIdentityCreated` ASC),
  CONSTRAINT `fk_passwordless_users1`
    FOREIGN KEY (`idUser`)
    REFERENCES `melisa`.`users` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_passwordless_identities1`
    FOREIGN KEY (`idIdentityCreated`)
    REFERENCES `melisa`.`identities` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `melisa`.`passwordlessEmails`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `melisa`.`passwordlessEmails` (
  `id` VARCHAR(36) NOT NULL,
  `idPasswordless` VARCHAR(36) NOT NULL,
  `idIdentityCreated` VARCHAR(36) NOT NULL,
  `active` TINYINT NOT NULL DEFAULT 1,
  `token` VARCHAR(60) NOT NULL,
  `email` VARCHAR(90) NOT NULL,
  `createdAt` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `dateExpiry` DATETIME NOT NULL,
  `idIdentityUpdated` VARCHAR(36) NULL,
  `updatedAt` DATETIME NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_passwordlessEmails_passwordless1_idx` (`idPasswordless` ASC),
  INDEX `fk_passwordlessEmails_identities1_idx` (`idIdentityCreated` ASC),
  UNIQUE INDEX `idPasswordless_email_UNIQUE` (`idPasswordless` ASC, `email` ASC),
  CONSTRAINT `fk_passwordlessEmails_passwordless1`
    FOREIGN KEY (`idPasswordless`)
    REFERENCES `melisa`.`passwordless` (`id`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_passwordlessEmails_identities1`
    FOREIGN KEY (`idIdentityCreated`)
    REFERENCES `melisa`.`identities` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
